-
  hosts: all

  tasks:
    - name: add nodejs repo
      apt_repository: repo='ppa:chris-lea/node.js' state=present

    - name: install nodejs
      apt: pkg=nodejs state=latest update_cache=yes

    - npm: name=gulp state=latest global=yes
